[theme]
base = ".streamlit/themes/dark_gray.toml"

[logger]

# Level of logging for Streamlit's internal logger: "error", "warning", "info", "debug"
# Default: "info"
level = "info"

# String format for logging messages
# Default: "%(asctime)s %(message)s"
messageFormat = "%(asctime)s %(name)s %(levelname)s %(message)s"